version: '3.8'

services:
  armed-app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version",]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s