version: '3.8'

services:
  armed-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      # Add your environment variables here
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_SLACK_ID=${AUTH_SLACK_ID}
      - AUTH_SLACK_SECRET=${AUTH_SLACK_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
